version: '3'

services:
  web:
    container_name: django_web
    build:
      context: .
    image: django-web
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
      - DBNAME
      - DBUSER
      - DBPASS
      - DBHOST
      - DBPORT
      - ALLOWED_HOSTS
    volumes:
      - .:/app
    #depends_on:
    #- db
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        sleep 180
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
        #gunicorn -b :8000 myproject.wsgi

# database for development
  db:
    container_name: django_mysqldb
    image: mysql:latest
    env_file: ./myproject/.env
    volumes:
      - newdb:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always

volumes:
  newdb:
    external: true
#mysqldb_german_site:
#external: true
