version: '3'

services:
  web:
    container_name: django_web
    build:
      context: .
    image: django-web
    ports:
      - 8000:8000
    env_file: ./myproject/.env
    volumes:
      - .:/app
    #depends_on:
    #- db
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py migrate
        gunicorn -b :8000 myproject.wsgi

# database for development
#   db:
#     container_name: django_mysqldb
#     image: mysql:latest
#     env_file: ./myproject/.env
#     volumes:
#       - mysqldb_german_site:/var/lib/mysql
#     ports:
#       - 3307:3306
#     restart: always
#
# volumes:
#   mysqldb_german_site:
#     external: true
